name: RVCK

on:
  push:
  # pull_request:
  #   types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  rvck:
    uses: OERV-RVCI/RVCK-pipeline/.github/workflows/rava-actions.yml@actions
    secrets:
      lava_token: ${{ secrets.LAVA_TOKEN }}
    # permissions:
    #   issues: write
    #   pull-requests: write
